#369 and #370: Add support for the clear chat room history event
igniterealtime/openfire-monitoring-plugin pull request #408
Opened 2024-12-06 13:12 UTC by hqv126

fixes #369
fixes #370

We can address both #369 and #370 by implementing the handling of the "clear chat history" event from Openfire. Openfire sends a "clear chat history" event in the following scenarios:

A room is destroyed, and no chat history should be preserved.
A "clear room history" command is issued during the lifetime of a chat room.
By tracking the archive, conversation, and participant data using a roomID, we can remove the relevant data when a "clear chat history" event is received.

An ofMucRoomStatus table is used to persistently store mappings between roomID and roomJID. This table also stores information on whether a room was destroyed, ensuring the same room ID cannot be reused and allowing the plugin to determine which rooms are still active. This data is loaded into ConversationManager.roomJIDToIDMap during the static initialisation of the class. Additionally, ofMucRoomStatus is kept up to date whenever roomJIDToIDMap changes. If the Openfire server instance is restarted, the correct and up-to-date room status data will be reloaded.

When a room is destroyed, in addition to ending the room conversation, both ofMucRoomStatus and ConversationManager.roomJIDToIDMap are updated.

2024-12-10 14:36 UTC, guusdk requested changes
Am I right to think that this will assign a room ID of `-1` to all conversations that preexist in the database? That would identify those conversations as being one-on-one chats, instead of group chats, right? I think that the database update script should do a 'migration' of sorts, so that all preexisting data (where needed) gets a valid identifier.

It also seems a bit awkward to have a `roomJIDtoIDMap`. Keeping this map in memory may introduce issues when clustering (where each of the cluster nodes would have it's own in-memory map). Maybe it's good to consider refactoring this a bit, and use a MUCRoomStatus object, that is a proper representation of a room, plus associated DAO objects?

2024-12-10 14:36 UTC, guusdk commented on src/database/monitoring_db2.sql
>    room                  VARCHAR(512),
Should the `room` and `isExernal` columns be moved to the new table?

2024-12-11 12:47 UTC, hqv126 commented
> Am I right to think that this will assign a room ID of `-1` to all conversations that preexist in the database? That would identify those conversations as being one-on-one chats, instead of group chats, right? I think that the database update script should do a 'migration' of sorts, so that all preexisting data (where needed) gets a valid identifier.

Do you do complex data migration using the sql update scripts? The things we would need to do would include:

- Create room IDs for existing conversations in the ofConversation table.
- Update the ofID table used by SequenceManager.
- Use the new room IDs to update the ofConParticipant and ofMessageArchive tables.
- Create a new ofMucRoomStatus table, populate it, and copy the isExternal data from the ofConversation table into it.
- Not sure how to populate the ofMucRoomStatus.roomDestroyed field at the moment.

2024-12-11 15:17 UTC, hqv126 commented
> It also seems a bit awkward to have a `roomJIDtoIDMap`. Keeping this map in memory may introduce issues when clustering (where each of the cluster nodes would have it's own in-memory map). Maybe it's good to consider refactoring this a bit, and use a MUCRoomStatus object, that is a proper representation of a room, plus associated DAO objects?

I've updated the code to group the access methods for ofMucRoomStatus into MUCRoomStatusDAO. The roomJIDtoIDMap is similar to ConversationManager.conversations. I’ll need to check with you about clustering.

2024-12-12 09:17 UTC, guusdk commented
> Will need to check with you on whether a data migration script is the best solution.

I'd _prefer_ to have an SQL script able to do this, but I recognize that this might not be practically achievable. I don't think that not doing a migration at all is an option: I expect that this basically corrupts preexisting data, leading to broken end-user functionality.

There is some precedent of having bits of Java code for one-time data migration. For examples of that, see the code in the ` org.jivesoftware.database.bugfix` package in the Openfire source code. Maybe we can use something similar in this plugin, if we need to.

2024-12-13 09:57 UTC, hqv126 commented
> org.jivesoftware.database.bugfix

org.jivesoftware.database.bugfix is in the openfire repo. Should I create a org.jivesoftware.database.bugfix package in the monitoring plugin to house a java script if needed?

2024-12-19 23:47 UTC, guusdk requested changes
I have serious concerns about this. On the one hand it out of the box generates errors upon first use, and has a SQL call which is clearly not correct (mismatched number of query parameters vs arguments supplied), but I've also got concerns about the overarching approach.

In particular the various maps that retain identifier-to-object relationships seem fragile. I believe that they duplicate state (from either other objects or the database), and their positioning/usage isn't well defined, leading to confusing usage patterns (where unnecessary room for issues is introduced).

There also is a scary blunt rebuild of Lucene indices when a room is removed. That is a non-trivial action, which basically does a full text scan of all archived messages in the database.

Finally, there are a number of other inconsistencies that I've flagged in individual review items.

Let's discuss how to move forward.

2024-12-19 23:47 UTC, guusdk commented on src/database/upgrade/9/monitoring_db2.sql
> +    roomID          INTEGER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
I don't have a DB2 instance to test this again, but a syntax checker dislikes the `GENERATED ALWAYS AS IDENTITY PRIMARY KEY` part.

2024-12-19 23:47 UTC, guusdk commented on src/database/upgrade/9/monitoring_hsqldb.sql
> +UPDATE ofConversation c
HSQLDB does not accept this UPDATE query syntax.

2024-12-19 23:47 UTC, guusdk commented on src/database/upgrade/9/monitoring_sqlserver.sql
> +INSERT INTO ofMucRoomStatus (SELECT * FROM #ofTmpStatus);
Syntax checker does not like this INSERT query, and fails on the `*` of the sub-select.

2025-01-02 13:08 UTC, guusdk commented on src/database/monitoring_oracle.sql
>    isExternal            NUMBER(2)      NOT NULL,
Seems to miss the index that's created for other databases.

2025-01-07 13:24 UTC, guusdk commented
Closing in favor of #411

2025-01-07 13:24 UTC, closed without merging